# Theme
theme:
  name: material
  language: en
  features:
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

site_name: Tech Docs
site_url: https://youngdeok.github.io/docs
site_author: Youngdeok Hwang

repo_name: docs
repo_url: https://github.com/youngdeok/docs

nav:
  - Welcome:
    - About the site: index.md
  - How to write:
    - Basic: how/write.md
    - Advance: how/advance.md

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Korean
      link: /ko/
      lang: ko

plugins:
  - git-revision-date
